<style>
  .star-wars-films {
    display: inline-block;
  }
</style>

<div class="star-wars-films">
  <ol>
      <?php foreach ($this->getStarWarsFilms() as $film): ?>
        <li>
          Title: <a target="_blank" href="http://google.com/search?q=<?= $film->title ?>"><b>"<?= $film->title ?>"</b></a>. Release:
          <i><?= $film->release_date ?></i>
        </li>
      <?php endforeach; ?>
  </ol>
</div>
<?php
//$block->getUrl('sss');